# Generated by Django 3.0.6 on 2020-09-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_view',
            field=models.BooleanField(default=True),
        ),
    ]
