# Generated by Django 3.0.6 on 2020-09-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_page_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_view',
            field=models.SlugField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.SlugField(blank=True, max_length=16, null=True),
        ),
    ]
