# Generated by Django 3.0.6 on 2020-09-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20200925_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
