# Generated by Django 3.0.6 on 2020-09-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='litres_url',
            field=models.URLField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='litres_url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='root_dir',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
