# Generated by Django 3.0.6 on 2020-10-16 08:00
# RenameField manually added

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20201015_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.RenameField(
            model_name='book',
            old_name='text',
            new_name='annotation'
        ),
    ]
