# Generated by Django 3.0.6 on 2021-07-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20201017_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.SlugField(blank=True, choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='eng',
            field=models.CharField(default='chess', max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
